change

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -66,12 +66,13 @@ terraform_action:
   dependencies:
     - terraform_plan
   script:
-    - echo "Executing Terraform action: $ACTION"
     - >
+      echo "Executing Terraform action: $ACTION";
       if [ "$ACTION" = "apply" ]; then
         terraform apply -auto-approve tfplan;
       elif [ "$ACTION" = "destroy" ]; then
         terraform destroy -auto-approve;
       else
-        echo "Invalid ACTION! Exiting..."; exit 1;
+        echo "Invalid ACTION! Exiting...";
+        exit 1;
       fi
